#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerData.ClassLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDELECTRONICOS01")]
	public partial class dcFactguracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    partial void InsertDETALLE_COMPROBANTE(DETALLE_COMPROBANTE instance);
    partial void UpdateDETALLE_COMPROBANTE(DETALLE_COMPROBANTE instance);
    partial void DeleteDETALLE_COMPROBANTE(DETALLE_COMPROBANTE instance);
    partial void InsertTBL_ROL(TBL_ROL instance);
    partial void UpdateTBL_ROL(TBL_ROL instance);
    partial void DeleteTBL_ROL(TBL_ROL instance);
    partial void InsertCOMPROBANTE(COMPROBANTE instance);
    partial void UpdateCOMPROBANTE(COMPROBANTE instance);
    partial void DeleteCOMPROBANTE(COMPROBANTE instance);
    #endregion
		
		public dcFactguracionDataContext() : 
				base(global::LayerData.ClassLibrary.Properties.Settings.Default.BDELECTRONICOS01ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcFactguracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFactguracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFactguracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFactguracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<DETALLE_COMPROBANTE> DETALLE_COMPROBANTE
		{
			get
			{
				return this.GetTable<DETALLE_COMPROBANTE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ROL> TBL_ROL
		{
			get
			{
				return this.GetTable<TBL_ROL>();
			}
		}
		
		public System.Data.Linq.Table<COMPROBANTE> COMPROBANTE
		{
			get
			{
				return this.GetTable<COMPROBANTE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateUsuario")]
		public ISingleResult<spUpdateUsuarioResult> spUpdateUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, correo, password, apellidos, nombres, rol);
			return ((ISingleResult<spUpdateUsuarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_correo;
		
		private string _usu_password;
		
		private string _usu_apellidos;
		
		private string _usu_nombres;
		
		private char _usu_status;
		
		private System.DateTime _usu_add;
		
		private byte _rol_id;
		
		private EntityRef<TBL_ROL> _TBL_ROL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_passwordChanging(string value);
    partial void Onusu_passwordChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_statusChanging(char value);
    partial void Onusu_statusChanged();
    partial void Onusu_addChanging(System.DateTime value);
    partial void Onusu_addChanged();
    partial void Onrol_idChanging(byte value);
    partial void Onrol_idChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			this._TBL_ROL = default(EntityRef<TBL_ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_password
		{
			get
			{
				return this._usu_password;
			}
			set
			{
				if ((this._usu_password != value))
				{
					this.Onusu_passwordChanging(value);
					this.SendPropertyChanging();
					this._usu_password = value;
					this.SendPropertyChanged("usu_password");
					this.Onusu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_status", DbType="Char(1) NOT NULL")]
		public char usu_status
		{
			get
			{
				return this._usu_status;
			}
			set
			{
				if ((this._usu_status != value))
				{
					this.Onusu_statusChanging(value);
					this.SendPropertyChanging();
					this._usu_status = value;
					this.SendPropertyChanged("usu_status");
					this.Onusu_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_add", DbType="DateTime NOT NULL")]
		public System.DateTime usu_add
		{
			get
			{
				return this._usu_add;
			}
			set
			{
				if ((this._usu_add != value))
				{
					this.Onusu_addChanging(value);
					this.SendPropertyChanging();
					this._usu_add = value;
					this.SendPropertyChanged("usu_add");
					this.Onusu_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._TBL_ROL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_ROL", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public TBL_ROL TBL_ROL
		{
			get
			{
				return this._TBL_ROL.Entity;
			}
			set
			{
				TBL_ROL previousValue = this._TBL_ROL.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ROL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ROL.Entity = null;
						previousValue.TBL_USUARIO.Remove(this);
					}
					this._TBL_ROL.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIO.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(byte);
					}
					this.SendPropertyChanged("TBL_ROL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_COMPROBANTE")]
	public partial class DETALLE_COMPROBANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dec_id;
		
		private string _dec_codigoproducto;
		
		private int _dec_cantidad;
		
		private string _dec_descripcion;
		
		private decimal _dec_precio;
		
		private decimal _dec_descuento;
		
		private decimal _dec_iva0;
		
		private decimal _dec_ivagravado;
		
		private decimal _dec_valortotal;
		
		private long _com_id;
		
		private System.DateTime _com_fecha;
		
		private EntityRef<COMPROBANTE> _COMPROBANTE;
		
		private EntityRef<COMPROBANTE> _COMPROBANTE1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondec_idChanging(int value);
    partial void Ondec_idChanged();
    partial void Ondec_codigoproductoChanging(string value);
    partial void Ondec_codigoproductoChanged();
    partial void Ondec_cantidadChanging(int value);
    partial void Ondec_cantidadChanged();
    partial void Ondec_descripcionChanging(string value);
    partial void Ondec_descripcionChanged();
    partial void Ondec_precioChanging(decimal value);
    partial void Ondec_precioChanged();
    partial void Ondec_descuentoChanging(decimal value);
    partial void Ondec_descuentoChanged();
    partial void Ondec_iva0Changing(decimal value);
    partial void Ondec_iva0Changed();
    partial void Ondec_ivagravadoChanging(decimal value);
    partial void Ondec_ivagravadoChanged();
    partial void Ondec_valortotalChanging(decimal value);
    partial void Ondec_valortotalChanged();
    partial void Oncom_idChanging(long value);
    partial void Oncom_idChanged();
    partial void Oncom_fechaChanging(System.DateTime value);
    partial void Oncom_fechaChanged();
    #endregion
		
		public DETALLE_COMPROBANTE()
		{
			this._COMPROBANTE = default(EntityRef<COMPROBANTE>);
			this._COMPROBANTE1 = default(EntityRef<COMPROBANTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dec_id
		{
			get
			{
				return this._dec_id;
			}
			set
			{
				if ((this._dec_id != value))
				{
					this.Ondec_idChanging(value);
					this.SendPropertyChanging();
					this._dec_id = value;
					this.SendPropertyChanged("dec_id");
					this.Ondec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_codigoproducto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string dec_codigoproducto
		{
			get
			{
				return this._dec_codigoproducto;
			}
			set
			{
				if ((this._dec_codigoproducto != value))
				{
					this.Ondec_codigoproductoChanging(value);
					this.SendPropertyChanging();
					this._dec_codigoproducto = value;
					this.SendPropertyChanged("dec_codigoproducto");
					this.Ondec_codigoproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_cantidad", DbType="Int NOT NULL")]
		public int dec_cantidad
		{
			get
			{
				return this._dec_cantidad;
			}
			set
			{
				if ((this._dec_cantidad != value))
				{
					this.Ondec_cantidadChanging(value);
					this.SendPropertyChanging();
					this._dec_cantidad = value;
					this.SendPropertyChanged("dec_cantidad");
					this.Ondec_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_descripcion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dec_descripcion
		{
			get
			{
				return this._dec_descripcion;
			}
			set
			{
				if ((this._dec_descripcion != value))
				{
					this.Ondec_descripcionChanging(value);
					this.SendPropertyChanging();
					this._dec_descripcion = value;
					this.SendPropertyChanged("dec_descripcion");
					this.Ondec_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_precio", DbType="Decimal(8,4) NOT NULL")]
		public decimal dec_precio
		{
			get
			{
				return this._dec_precio;
			}
			set
			{
				if ((this._dec_precio != value))
				{
					this.Ondec_precioChanging(value);
					this.SendPropertyChanging();
					this._dec_precio = value;
					this.SendPropertyChanged("dec_precio");
					this.Ondec_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_descuento", DbType="Decimal(8,4) NOT NULL")]
		public decimal dec_descuento
		{
			get
			{
				return this._dec_descuento;
			}
			set
			{
				if ((this._dec_descuento != value))
				{
					this.Ondec_descuentoChanging(value);
					this.SendPropertyChanging();
					this._dec_descuento = value;
					this.SendPropertyChanged("dec_descuento");
					this.Ondec_descuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_iva0", DbType="Decimal(8,4) NOT NULL")]
		public decimal dec_iva0
		{
			get
			{
				return this._dec_iva0;
			}
			set
			{
				if ((this._dec_iva0 != value))
				{
					this.Ondec_iva0Changing(value);
					this.SendPropertyChanging();
					this._dec_iva0 = value;
					this.SendPropertyChanged("dec_iva0");
					this.Ondec_iva0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_ivagravado", DbType="Decimal(8,4) NOT NULL")]
		public decimal dec_ivagravado
		{
			get
			{
				return this._dec_ivagravado;
			}
			set
			{
				if ((this._dec_ivagravado != value))
				{
					this.Ondec_ivagravadoChanging(value);
					this.SendPropertyChanging();
					this._dec_ivagravado = value;
					this.SendPropertyChanged("dec_ivagravado");
					this.Ondec_ivagravadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_valortotal", DbType="Decimal(8,4) NOT NULL")]
		public decimal dec_valortotal
		{
			get
			{
				return this._dec_valortotal;
			}
			set
			{
				if ((this._dec_valortotal != value))
				{
					this.Ondec_valortotalChanging(value);
					this.SendPropertyChanging();
					this._dec_valortotal = value;
					this.SendPropertyChanged("dec_valortotal");
					this.Ondec_valortotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long com_id
		{
			get
			{
				return this._com_id;
			}
			set
			{
				if ((this._com_id != value))
				{
					if ((this._COMPROBANTE.HasLoadedOrAssignedValue || this._COMPROBANTE1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncom_idChanging(value);
					this.SendPropertyChanging();
					this._com_id = value;
					this.SendPropertyChanged("com_id");
					this.Oncom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_fecha", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime com_fecha
		{
			get
			{
				return this._com_fecha;
			}
			set
			{
				if ((this._com_fecha != value))
				{
					if ((this._COMPROBANTE.HasLoadedOrAssignedValue || this._COMPROBANTE1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncom_fechaChanging(value);
					this.SendPropertyChanging();
					this._com_fecha = value;
					this.SendPropertyChanged("com_fecha");
					this.Oncom_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPROBANTE_DETALLE_COMPROBANTE", Storage="_COMPROBANTE", ThisKey="com_id,com_fecha", OtherKey="com_id,com_fecha", IsForeignKey=true)]
		public COMPROBANTE COMPROBANTE
		{
			get
			{
				return this._COMPROBANTE.Entity;
			}
			set
			{
				COMPROBANTE previousValue = this._COMPROBANTE.Entity;
				if (((previousValue != value) 
							|| (this._COMPROBANTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMPROBANTE.Entity = null;
						previousValue.DETALLE_COMPROBANTE.Remove(this);
					}
					this._COMPROBANTE.Entity = value;
					if ((value != null))
					{
						value.DETALLE_COMPROBANTE.Add(this);
						this._com_id = value.com_id;
						this._com_fecha = value.com_fecha;
					}
					else
					{
						this._com_id = default(long);
						this._com_fecha = default(System.DateTime);
					}
					this.SendPropertyChanged("COMPROBANTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPROBANTE_DETALLE_COMPROBANTE1", Storage="_COMPROBANTE1", ThisKey="com_id,com_fecha", OtherKey="com_id,com_fecha", IsForeignKey=true)]
		public COMPROBANTE COMPROBANTE1
		{
			get
			{
				return this._COMPROBANTE1.Entity;
			}
			set
			{
				COMPROBANTE previousValue = this._COMPROBANTE1.Entity;
				if (((previousValue != value) 
							|| (this._COMPROBANTE1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMPROBANTE1.Entity = null;
						previousValue.DETALLE_COMPROBANTE1.Remove(this);
					}
					this._COMPROBANTE1.Entity = value;
					if ((value != null))
					{
						value.DETALLE_COMPROBANTE1.Add(this);
						this._com_id = value.com_id;
						this._com_fecha = value.com_fecha;
					}
					else
					{
						this._com_id = default(long);
						this._com_fecha = default(System.DateTime);
					}
					this.SendPropertyChanged("COMPROBANTE1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ROL")]
	public partial class TBL_ROL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _rol_id;
		
		private string _rol_descripcion;
		
		private char _rol_status;
		
		private System.DateTime _rol_add;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(byte value);
    partial void Onrol_idChanged();
    partial void Onrol_descripcionChanging(string value);
    partial void Onrol_descripcionChanged();
    partial void Onrol_statusChanging(char value);
    partial void Onrol_statusChanged();
    partial void Onrol_addChanging(System.DateTime value);
    partial void Onrol_addChanged();
    #endregion
		
		public TBL_ROL()
		{
			this._TBL_USUARIO = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIO), new Action<TBL_USUARIO>(this.detach_TBL_USUARIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_descripcion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string rol_descripcion
		{
			get
			{
				return this._rol_descripcion;
			}
			set
			{
				if ((this._rol_descripcion != value))
				{
					this.Onrol_descripcionChanging(value);
					this.SendPropertyChanging();
					this._rol_descripcion = value;
					this.SendPropertyChanged("rol_descripcion");
					this.Onrol_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_status", DbType="Char(1) NOT NULL")]
		public char rol_status
		{
			get
			{
				return this._rol_status;
			}
			set
			{
				if ((this._rol_status != value))
				{
					this.Onrol_statusChanging(value);
					this.SendPropertyChanging();
					this._rol_status = value;
					this.SendPropertyChanged("rol_status");
					this.Onrol_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_add", DbType="DateTime NOT NULL")]
		public System.DateTime rol_add
		{
			get
			{
				return this._rol_add;
			}
			set
			{
				if ((this._rol_add != value))
				{
					this.Onrol_addChanging(value);
					this.SendPropertyChanging();
					this._rol_add = value;
					this.SendPropertyChanged("rol_add");
					this.Onrol_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_USUARIO", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this._TBL_USUARIO;
			}
			set
			{
				this._TBL_USUARIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = this;
		}
		
		private void detach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMPROBANTE")]
	public partial class COMPROBANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _com_id;
		
		private System.DateTime _com_fecha;
		
		private int _com_orden;
		
		private string _com_identificacion;
		
		private string _com_apellidos;
		
		private string _com_nombres;
		
		private string _com_direccion;
		
		private string _com_telefono;
		
		private string _com_establecimiento;
		
		private string _com_emision;
		
		private string _com_secuencial;
		
		private string _com_claveacceso;
		
		private string _com_numeroautorizacion;
		
		private string _com_fechaautorizacion;
		
		private decimal _com_subtotal0;
		
		private decimal _com_subtotalgravado;
		
		private decimal _com_iva0;
		
		private decimal _com_ivagravado;
		
		private string _com_estadosri;
		
		private string _com_mensajesri;
		
		private System.DateTime _com_add;
		
		private char _com_status;
		
		private System.Nullable<System.DateTime> _com_update;
		
		private System.Nullable<System.DateTime> _com_delete;
		
		private string _com_tipoIdentificacion;
		
		private decimal _com_total;
		
		private decimal _com_totalDescuento;
		
		private EntitySet<DETALLE_COMPROBANTE> _DETALLE_COMPROBANTE;
		
		private EntitySet<DETALLE_COMPROBANTE> _DETALLE_COMPROBANTE1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncom_idChanging(long value);
    partial void Oncom_idChanged();
    partial void Oncom_fechaChanging(System.DateTime value);
    partial void Oncom_fechaChanged();
    partial void Oncom_ordenChanging(int value);
    partial void Oncom_ordenChanged();
    partial void Oncom_identificacionChanging(string value);
    partial void Oncom_identificacionChanged();
    partial void Oncom_apellidosChanging(string value);
    partial void Oncom_apellidosChanged();
    partial void Oncom_nombresChanging(string value);
    partial void Oncom_nombresChanged();
    partial void Oncom_direccionChanging(string value);
    partial void Oncom_direccionChanged();
    partial void Oncom_telefonoChanging(string value);
    partial void Oncom_telefonoChanged();
    partial void Oncom_establecimientoChanging(string value);
    partial void Oncom_establecimientoChanged();
    partial void Oncom_emisionChanging(string value);
    partial void Oncom_emisionChanged();
    partial void Oncom_secuencialChanging(string value);
    partial void Oncom_secuencialChanged();
    partial void Oncom_claveaccesoChanging(string value);
    partial void Oncom_claveaccesoChanged();
    partial void Oncom_numeroautorizacionChanging(string value);
    partial void Oncom_numeroautorizacionChanged();
    partial void Oncom_fechaautorizacionChanging(string value);
    partial void Oncom_fechaautorizacionChanged();
    partial void Oncom_subtotal0Changing(decimal value);
    partial void Oncom_subtotal0Changed();
    partial void Oncom_subtotalgravadoChanging(decimal value);
    partial void Oncom_subtotalgravadoChanged();
    partial void Oncom_iva0Changing(decimal value);
    partial void Oncom_iva0Changed();
    partial void Oncom_ivagravadoChanging(decimal value);
    partial void Oncom_ivagravadoChanged();
    partial void Oncom_estadosriChanging(string value);
    partial void Oncom_estadosriChanged();
    partial void Oncom_mensajesriChanging(string value);
    partial void Oncom_mensajesriChanged();
    partial void Oncom_addChanging(System.DateTime value);
    partial void Oncom_addChanged();
    partial void Oncom_statusChanging(char value);
    partial void Oncom_statusChanged();
    partial void Oncom_updateChanging(System.Nullable<System.DateTime> value);
    partial void Oncom_updateChanged();
    partial void Oncom_deleteChanging(System.Nullable<System.DateTime> value);
    partial void Oncom_deleteChanged();
    partial void Oncom_tipoIdentificacionChanging(string value);
    partial void Oncom_tipoIdentificacionChanged();
    partial void Oncom_totalChanging(decimal value);
    partial void Oncom_totalChanged();
    partial void Oncom_totalDescuentoChanging(decimal value);
    partial void Oncom_totalDescuentoChanged();
    #endregion
		
		public COMPROBANTE()
		{
			this._DETALLE_COMPROBANTE = new EntitySet<DETALLE_COMPROBANTE>(new Action<DETALLE_COMPROBANTE>(this.attach_DETALLE_COMPROBANTE), new Action<DETALLE_COMPROBANTE>(this.detach_DETALLE_COMPROBANTE));
			this._DETALLE_COMPROBANTE1 = new EntitySet<DETALLE_COMPROBANTE>(new Action<DETALLE_COMPROBANTE>(this.attach_DETALLE_COMPROBANTE1), new Action<DETALLE_COMPROBANTE>(this.detach_DETALLE_COMPROBANTE1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long com_id
		{
			get
			{
				return this._com_id;
			}
			set
			{
				if ((this._com_id != value))
				{
					this.Oncom_idChanging(value);
					this.SendPropertyChanging();
					this._com_id = value;
					this.SendPropertyChanged("com_id");
					this.Oncom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_fecha", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime com_fecha
		{
			get
			{
				return this._com_fecha;
			}
			set
			{
				if ((this._com_fecha != value))
				{
					this.Oncom_fechaChanging(value);
					this.SendPropertyChanging();
					this._com_fecha = value;
					this.SendPropertyChanged("com_fecha");
					this.Oncom_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_orden", DbType="Int NOT NULL")]
		public int com_orden
		{
			get
			{
				return this._com_orden;
			}
			set
			{
				if ((this._com_orden != value))
				{
					this.Oncom_ordenChanging(value);
					this.SendPropertyChanging();
					this._com_orden = value;
					this.SendPropertyChanged("com_orden");
					this.Oncom_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_identificacion", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string com_identificacion
		{
			get
			{
				return this._com_identificacion;
			}
			set
			{
				if ((this._com_identificacion != value))
				{
					this.Oncom_identificacionChanging(value);
					this.SendPropertyChanging();
					this._com_identificacion = value;
					this.SendPropertyChanged("com_identificacion");
					this.Oncom_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string com_apellidos
		{
			get
			{
				return this._com_apellidos;
			}
			set
			{
				if ((this._com_apellidos != value))
				{
					this.Oncom_apellidosChanging(value);
					this.SendPropertyChanging();
					this._com_apellidos = value;
					this.SendPropertyChanged("com_apellidos");
					this.Oncom_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string com_nombres
		{
			get
			{
				return this._com_nombres;
			}
			set
			{
				if ((this._com_nombres != value))
				{
					this.Oncom_nombresChanging(value);
					this.SendPropertyChanging();
					this._com_nombres = value;
					this.SendPropertyChanged("com_nombres");
					this.Oncom_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_direccion", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string com_direccion
		{
			get
			{
				return this._com_direccion;
			}
			set
			{
				if ((this._com_direccion != value))
				{
					this.Oncom_direccionChanging(value);
					this.SendPropertyChanging();
					this._com_direccion = value;
					this.SendPropertyChanged("com_direccion");
					this.Oncom_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_telefono", DbType="NVarChar(10)")]
		public string com_telefono
		{
			get
			{
				return this._com_telefono;
			}
			set
			{
				if ((this._com_telefono != value))
				{
					this.Oncom_telefonoChanging(value);
					this.SendPropertyChanging();
					this._com_telefono = value;
					this.SendPropertyChanged("com_telefono");
					this.Oncom_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_establecimiento", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string com_establecimiento
		{
			get
			{
				return this._com_establecimiento;
			}
			set
			{
				if ((this._com_establecimiento != value))
				{
					this.Oncom_establecimientoChanging(value);
					this.SendPropertyChanging();
					this._com_establecimiento = value;
					this.SendPropertyChanged("com_establecimiento");
					this.Oncom_establecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_emision", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string com_emision
		{
			get
			{
				return this._com_emision;
			}
			set
			{
				if ((this._com_emision != value))
				{
					this.Oncom_emisionChanging(value);
					this.SendPropertyChanging();
					this._com_emision = value;
					this.SendPropertyChanged("com_emision");
					this.Oncom_emisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_secuencial", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string com_secuencial
		{
			get
			{
				return this._com_secuencial;
			}
			set
			{
				if ((this._com_secuencial != value))
				{
					this.Oncom_secuencialChanging(value);
					this.SendPropertyChanging();
					this._com_secuencial = value;
					this.SendPropertyChanged("com_secuencial");
					this.Oncom_secuencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_claveacceso", DbType="Char(49) NOT NULL", CanBeNull=false)]
		public string com_claveacceso
		{
			get
			{
				return this._com_claveacceso;
			}
			set
			{
				if ((this._com_claveacceso != value))
				{
					this.Oncom_claveaccesoChanging(value);
					this.SendPropertyChanging();
					this._com_claveacceso = value;
					this.SendPropertyChanged("com_claveacceso");
					this.Oncom_claveaccesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_numeroautorizacion", DbType="Char(49) NOT NULL", CanBeNull=false)]
		public string com_numeroautorizacion
		{
			get
			{
				return this._com_numeroautorizacion;
			}
			set
			{
				if ((this._com_numeroautorizacion != value))
				{
					this.Oncom_numeroautorizacionChanging(value);
					this.SendPropertyChanging();
					this._com_numeroautorizacion = value;
					this.SendPropertyChanged("com_numeroautorizacion");
					this.Oncom_numeroautorizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_fechaautorizacion", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string com_fechaautorizacion
		{
			get
			{
				return this._com_fechaautorizacion;
			}
			set
			{
				if ((this._com_fechaautorizacion != value))
				{
					this.Oncom_fechaautorizacionChanging(value);
					this.SendPropertyChanging();
					this._com_fechaautorizacion = value;
					this.SendPropertyChanged("com_fechaautorizacion");
					this.Oncom_fechaautorizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_subtotal0", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_subtotal0
		{
			get
			{
				return this._com_subtotal0;
			}
			set
			{
				if ((this._com_subtotal0 != value))
				{
					this.Oncom_subtotal0Changing(value);
					this.SendPropertyChanging();
					this._com_subtotal0 = value;
					this.SendPropertyChanged("com_subtotal0");
					this.Oncom_subtotal0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_subtotalgravado", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_subtotalgravado
		{
			get
			{
				return this._com_subtotalgravado;
			}
			set
			{
				if ((this._com_subtotalgravado != value))
				{
					this.Oncom_subtotalgravadoChanging(value);
					this.SendPropertyChanging();
					this._com_subtotalgravado = value;
					this.SendPropertyChanged("com_subtotalgravado");
					this.Oncom_subtotalgravadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_iva0", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_iva0
		{
			get
			{
				return this._com_iva0;
			}
			set
			{
				if ((this._com_iva0 != value))
				{
					this.Oncom_iva0Changing(value);
					this.SendPropertyChanging();
					this._com_iva0 = value;
					this.SendPropertyChanged("com_iva0");
					this.Oncom_iva0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_ivagravado", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_ivagravado
		{
			get
			{
				return this._com_ivagravado;
			}
			set
			{
				if ((this._com_ivagravado != value))
				{
					this.Oncom_ivagravadoChanging(value);
					this.SendPropertyChanging();
					this._com_ivagravado = value;
					this.SendPropertyChanged("com_ivagravado");
					this.Oncom_ivagravadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_estadosri", DbType="NVarChar(50)")]
		public string com_estadosri
		{
			get
			{
				return this._com_estadosri;
			}
			set
			{
				if ((this._com_estadosri != value))
				{
					this.Oncom_estadosriChanging(value);
					this.SendPropertyChanging();
					this._com_estadosri = value;
					this.SendPropertyChanged("com_estadosri");
					this.Oncom_estadosriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_mensajesri", DbType="NVarChar(200)")]
		public string com_mensajesri
		{
			get
			{
				return this._com_mensajesri;
			}
			set
			{
				if ((this._com_mensajesri != value))
				{
					this.Oncom_mensajesriChanging(value);
					this.SendPropertyChanging();
					this._com_mensajesri = value;
					this.SendPropertyChanged("com_mensajesri");
					this.Oncom_mensajesriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_add", DbType="DateTime NOT NULL")]
		public System.DateTime com_add
		{
			get
			{
				return this._com_add;
			}
			set
			{
				if ((this._com_add != value))
				{
					this.Oncom_addChanging(value);
					this.SendPropertyChanging();
					this._com_add = value;
					this.SendPropertyChanged("com_add");
					this.Oncom_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_status", DbType="Char(1) NOT NULL")]
		public char com_status
		{
			get
			{
				return this._com_status;
			}
			set
			{
				if ((this._com_status != value))
				{
					this.Oncom_statusChanging(value);
					this.SendPropertyChanging();
					this._com_status = value;
					this.SendPropertyChanged("com_status");
					this.Oncom_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_update", DbType="DateTime")]
		public System.Nullable<System.DateTime> com_update
		{
			get
			{
				return this._com_update;
			}
			set
			{
				if ((this._com_update != value))
				{
					this.Oncom_updateChanging(value);
					this.SendPropertyChanging();
					this._com_update = value;
					this.SendPropertyChanged("com_update");
					this.Oncom_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_delete", DbType="DateTime")]
		public System.Nullable<System.DateTime> com_delete
		{
			get
			{
				return this._com_delete;
			}
			set
			{
				if ((this._com_delete != value))
				{
					this.Oncom_deleteChanging(value);
					this.SendPropertyChanging();
					this._com_delete = value;
					this.SendPropertyChanged("com_delete");
					this.Oncom_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_tipoIdentificacion", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string com_tipoIdentificacion
		{
			get
			{
				return this._com_tipoIdentificacion;
			}
			set
			{
				if ((this._com_tipoIdentificacion != value))
				{
					this.Oncom_tipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._com_tipoIdentificacion = value;
					this.SendPropertyChanged("com_tipoIdentificacion");
					this.Oncom_tipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_total", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_total
		{
			get
			{
				return this._com_total;
			}
			set
			{
				if ((this._com_total != value))
				{
					this.Oncom_totalChanging(value);
					this.SendPropertyChanging();
					this._com_total = value;
					this.SendPropertyChanged("com_total");
					this.Oncom_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_totalDescuento", DbType="Decimal(8,4) NOT NULL")]
		public decimal com_totalDescuento
		{
			get
			{
				return this._com_totalDescuento;
			}
			set
			{
				if ((this._com_totalDescuento != value))
				{
					this.Oncom_totalDescuentoChanging(value);
					this.SendPropertyChanging();
					this._com_totalDescuento = value;
					this.SendPropertyChanged("com_totalDescuento");
					this.Oncom_totalDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPROBANTE_DETALLE_COMPROBANTE", Storage="_DETALLE_COMPROBANTE", ThisKey="com_id,com_fecha", OtherKey="com_id,com_fecha")]
		public EntitySet<DETALLE_COMPROBANTE> DETALLE_COMPROBANTE
		{
			get
			{
				return this._DETALLE_COMPROBANTE;
			}
			set
			{
				this._DETALLE_COMPROBANTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMPROBANTE_DETALLE_COMPROBANTE1", Storage="_DETALLE_COMPROBANTE1", ThisKey="com_id,com_fecha", OtherKey="com_id,com_fecha")]
		public EntitySet<DETALLE_COMPROBANTE> DETALLE_COMPROBANTE1
		{
			get
			{
				return this._DETALLE_COMPROBANTE1;
			}
			set
			{
				this._DETALLE_COMPROBANTE1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_COMPROBANTE(DETALLE_COMPROBANTE entity)
		{
			this.SendPropertyChanging();
			entity.COMPROBANTE = this;
		}
		
		private void detach_DETALLE_COMPROBANTE(DETALLE_COMPROBANTE entity)
		{
			this.SendPropertyChanging();
			entity.COMPROBANTE = null;
		}
		
		private void attach_DETALLE_COMPROBANTE1(DETALLE_COMPROBANTE entity)
		{
			this.SendPropertyChanging();
			entity.COMPROBANTE1 = this;
		}
		
		private void detach_DETALLE_COMPROBANTE1(DETALLE_COMPROBANTE entity)
		{
			this.SendPropertyChanging();
			entity.COMPROBANTE1 = null;
		}
	}
	
	public partial class spUpdateUsuarioResult
	{
		
		private int _Column1;
		
		public spUpdateUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
